Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "dockerhost"

  config.vm.provision "shell", path: "provision.sh"


  config.vm.define "dockerhost" do |dockerhost|

    dockerhost.vm.hostname = "dockerhost"

    dockerhost.vm.network "private_network", ip: "172.31.0.205"

  end

 end
